# theme-specific options;
# for a detailed explanation and many more options see
# https://mcshelby.github.io/hugo-theme-relearn/configuration/reference/index.html#annotated-configuration-options

# recommended theme parameter
author.name = 'Captain Hugo'

# logo image and title
logo = { src = '/images/logo.svg?inlinecontent' } # a global resource called `/images/logo.<TYPE>` will be selected automatically; nevertheless if you want to color an SVG it has to be inlined and so must be set manually here
linkTitle = "Purple \nPulpo"

# add some error checking for links
urlExternalCheck = true # this may be expensive during build, you may want to activate it only occasionally
include.errorlevel = 'warning'
image.errorlevel = 'warning'
link.errorlevel = 'warning'
openapi.errorlevel = 'warning'

# specific image effect for this showcase;
imageEffects.purple = false

# specific variant parameter for this showcase; you have the choice
# between many more predefined variants and even can configure your own;
# see the themes documentation
[[themeVariant]]
  identifier = 'auto'
  name = 'Auto'
  auto = [ 'learn', 'neon' ]
[[themeVariant]]
  identifier = 'neon'
  name = 'Dark'
[[themeVariant]]
  identifier = 'learn'
  name = 'Light'
