baseURL = "/"
languageCode = "en-US"
DefaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "../.."
MetaDataFormat = "yaml"

[params]
  editURL = "https://github.com/matcornic/hugo-learn-doc/edit/master/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true # default to false
  disableSearch = false # default to false
  ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]
